package xyz.yanghailong.orgdemo.org.pojo;

public class VOrg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org.org_id
     *
     * @mbggenerated
     */
    private Integer orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org.left
     *
     * @mbggenerated
     */
    private Integer left;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org.right
     *
     * @mbggenerated
     */
    private Integer right;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org.layer
     *
     * @mbggenerated
     */
    private Integer layer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_org.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org.org_id
     *
     * @return the value of v_org.org_id
     *
     * @mbggenerated
     */
    public Integer getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org.org_id
     *
     * @param orgId the value for v_org.org_id
     *
     * @mbggenerated
     */
    public void setOrgId(Integer orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org.name
     *
     * @return the value of v_org.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org.name
     *
     * @param name the value for v_org.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org.left
     *
     * @return the value of v_org.left
     *
     * @mbggenerated
     */
    public Integer getLeft() {
        return left;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org.left
     *
     * @param left the value for v_org.left
     *
     * @mbggenerated
     */
    public void setLeft(Integer left) {
        this.left = left;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org.right
     *
     * @return the value of v_org.right
     *
     * @mbggenerated
     */
    public Integer getRight() {
        return right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org.right
     *
     * @param right the value for v_org.right
     *
     * @mbggenerated
     */
    public void setRight(Integer right) {
        this.right = right;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org.layer
     *
     * @return the value of v_org.layer
     *
     * @mbggenerated
     */
    public Integer getLayer() {
        return layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org.layer
     *
     * @param layer the value for v_org.layer
     *
     * @mbggenerated
     */
    public void setLayer(Integer layer) {
        this.layer = layer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_org.desc
     *
     * @return the value of v_org.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_org.desc
     *
     * @param desc the value for v_org.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}